name: Run Tests for Monorepo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  be-tests:
    name: Run BE Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 

      - name: Install and Test BE
        working-directory: ./BE
        run: |
          npm install
          npm run test

 
  fe-tests:
    name: Run FE Tests
    runs-on: ubuntu-latest

    needs: be-tests 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 

      - name: Install and Start BE
        run: |
          npm install --prefix ./BE
          npm run dev --prefix ./BE &
          sleep 10 # Espera para asegurarse de que el servidor está listo

      - name: Install and Test FE
        run: |
          npm install --prefix ./FE
          npm run dev --prefix ./FE &
          sleep 10 # Espera para que FE esté listo
          npm run cypress run --prefix ./FE
